/**
 * Generated files for local AI agents: GUIDE.md, haptic-knowledge/README.md,
 * root AGENTS.md / CLAUDE.md, insights.md template and catalog.json.
 * Text only; file writing lives in hapticKnowledge.ts (KnowledgeFolder).
 */
import type { EditorDocument } from '@/utils/editorFolder'
import { EFFECT_RANGES, RECIPE_RANGES } from '@/utils/effectRanges'
import { computeFeatures, mixToMono, FEATURE_BANDS, DB_FLOOR, type HapticFeatures } from '@/utils/hapticFeatures'

const header = (studioVersion: string) => `<!-- generated by Hapbeat Studio v${studioVersion} — do not edit (overwritten on every open) -->`

export function guideMarkdown(studioVersion: string): string {
  return `${header(studioVersion)}
# Hapbeat haptic design — guide for AI agents

> 日本語要約: このフォルダは Hapbeat Studio の波形エディタ用フォルダです。AI エージェントは \`hapbeat-agent/inbox/\` に試行リクエスト（JSON）を置き、ユーザーが Studio で各候補を Hapbeat で触って評価します。評価は \`haptic-knowledge/\` に蓄積されるので、次の提案前に必ず読んでください。Studio は LLM を呼びません。

## MCP tools or files

If a \`hapbeat\` MCP server is available (\`hapbeat-helper mcp\`), prefer its tools: \`get_guide\` → \`get_knowledge\` → \`submit_trial\` → \`wait_for_rating\`. They use the same formats and knowledge base as the files described below. Without it, do the same through the files (\`hapbeat-agent/inbox/\`).

## Purpose

You help the user design vibration (haptic) clips for Hapbeat, a wearable vibrotactile device, from verbal descriptions such as onomatopoeia ("ごわごわ", "ざらざら"). You cannot feel vibration; the user can. So you propose small sets of candidates, the user rates them on the device in Hapbeat Studio, and the ratings accumulate as a knowledge base that you must read before proposing again.

## Folder layout

\`\`\`
<editor folder>/
  .hapbeat-editor/        Studio internal cache (decoded audio, settings). Never read or write.
  adjust/<project>/<sound|haptic>/
    <material>.json       "Adjust" of an event material in Studio: its effect chain (versioned).
    <material>.original.wav  The material before adjusting (16-bit WAV).
  exports/                User exports.
  hapbeat-agent/
    GUIDE.md              This file (generated).
    catalog.json          Clips in the editor, their features, and parameter ranges (generated).
    inbox/                Put trial requests here: <trialId>.json
    inbox/_rejected/      Invalid requests are moved here with <trialId>.error.txt explaining why.
    sources/              Put source audio you generated (WAV) here.
    outbox/               Messages from the user in Studio to you: <YYYYMMDD-HHmmss>-<rand>.json (see "Messages from Studio").
    outbox/_read/         Move each message here after reading it.
  haptic-knowledge/
    README.md             Structure of the knowledge base (generated).
    dimensions.json       Perceptual dimensions and vocabulary (human-edited source of truth).
    insights.md           Human/agent notes. Agents may only append to the "Proposed" section.
    index.json            Derived: vocabulary list and trial list.
    terms/<slug>.json     Derived: per-term aggregation of ratings.
    trials/<YYYY-MM>/<trialId>/
      trial.json          Accepted request + receivedAt + studioVersion.
      request.json        Your original request file (moved from inbox).
      candidates/<cid>.json  Resolved spec + features (+ error if rendering failed).
      audio/<cid>.wav     Rendered candidate, 48 kHz mono 16-bit.
      rating.json         The user's rating (latest) + history.
\`\`\`

## Recommended workflow

1. Read \`haptic-knowledge/index.json\`, then the relevant \`terms/<slug>.json\` (compare \`exemplars\` and the feature differences between \`good\`, \`tooWeak\` and \`tooStrong\`) and the "Confirmed" section of \`insights.md\`.
2. Pick ONE hypothesis axis and make 2–4 candidates along it (for example AM depth 0.4 / 0.7 / 0.95). Keep everything else fixed so the rating is interpretable.
3. Write the request to \`hapbeat-agent/inbox/<trialId>.json\` and ask the user to rate it in Studio (Waveform editor → AI trials). Wait for the rating as in "Receiving ratings".
4. Read \`haptic-knowledge/trials/*/<trialId>/rating.json\`. Use \`overall\` (with its \`verdict\`), \`directions\` ("should be more …"), \`comment\` and \`useRange\` to build the next candidates, and set \`parentTrial\` to the previous trial id.
5. When a tendency is consistent over 3 or more trials, append it to the "Proposed" section of \`insights.md\` with evidence (trialId/candidateId). Only the user moves items to "Confirmed".

Write the inbox file atomically if you can (write \`<trialId>.json.tmp\`, then rename). Studio only picks up \`*.json\` files and waits until a file has been unchanged for about 1.5 s.

## Trial request \`hapbeat-trial@1\` (you → Studio)

\`\`\`json
{
  "format": "hapbeat-trial@1",
  "id": "20260929-1530-gowagowa-01",
  "intent": "modify",
  "prompt": "布の音をもっとゴワゴワに",
  "terms": ["ごわごわ"],
  "parentTrial": "20260929-1510-gowagowa-00",
  "agent": { "name": "claude-code", "model": "claude-opus-5-5" },
  "rationale": "Roughness seems to follow AM depth; sweep depth at 18 Hz.",
  "knowledgeUsed": ["terms/ごわごわ.json#exemplars[0]"],
  "candidates": [
    {
      "id": "A",
      "label": "LPF 200 Hz",
      "hypothesis": "lower centroid feels heavier",
      "source": { "kind": "clip", "clipId": "<id from catalog.json>" },
      "effects": [ { "type": "lpf", "frequency": 200, "Q": 0.7 } ]
    }
  ]
}
\`\`\`

- \`id\`: /^[A-Za-z0-9_-]{1,80}$/ and must equal the file name without \`.json\`. Must be new.
- \`intent\`: \`"modify"\` (process existing material) or \`"create"\` (from scratch).
- \`prompt\`: the user's original request (required, ≤ 2000 chars). \`terms\`: 1–5 target words (≤ 40 chars each).
- Optional: \`parentTrial\`, \`agent\`, \`rationale\` (≤ 4000 chars), \`knowledgeUsed\`, \`project\`, \`scene\`, \`kind\`, \`target\`.
- \`project\` (optional): editor project label, 1–80 characters without leading/trailing spaces. Adopted candidates are filed under this project in the editor's clip list; reuse a \`project\` value from catalog.json clips to add to an existing project.
- \`kind\` (optional): \`"oneshot"\` (one event: a hit, a footstep), \`"loop"\` (a continuous texture or hum) or \`"sequence"\` (a repeated series such as consecutive footsteps; reserved — rated like the others for now). The rating form hides the regularity / continuity dimensions for \`"oneshot"\`. When omitted, Studio infers it from the scene cue (a loop cue → loop) and the candidates' length (all ≤ 2 s → oneshot).
- \`target\` (optional, default \`"haptic"\`): \`"sound"\` when the trial designs the event's sound effect instead of its haptic. Decide the sound of an event first, then its haptic to match it. Sound candidates are rendered at 48 kHz full band and auditioned on the PC only (never sent to a device); their ratings have overall / term match / comment only and are not aggregated into \`haptic-knowledge/terms/\`. While auditioning a haptic candidate for an event whose sound is decided, Studio plays that sound with it.
- \`scene\` (optional): \`{ "project": "trex-encounter", "cues": ["roar", "roar_impact"] }\` — the game moment the haptic is for. \`project\` is the game project's name (\`project_name\` in its \`Saved/HapticViewer/viewer-lib.json\`), \`cues\` 1–20 cue names from its cue table (/^[A-Za-z0-9_.-]{1,80}$/), optionally with a variant as \`"cue:variant"\` (e.g. \`"footstep:approach"\`). The first cue is the event a candidate is decided for in Studio. The video shown by default is the earliest recorded moment of any of the cues; set the optional \`clip\` (a file name in \`Saved/HapticViewer/\`, e.g. \`"01_footstep-approach_both_t001.3s.mp4"\`, one of the clips of those cues) to show a specific moment, e.g. when a later one hides the action. A clip the user picks in Studio for the trial wins over both. While that project is open in Studio's Scene tab, the editor's Scene video panel shows the recorded clip of that moment and plays it with each audition, so the user rates the candidates against the game footage. Omit it when the trial is not for a recorded game moment. \`context\` (optional, 0–20 cue names in the same form, none of \`cues\`): the cues that sound around the target in the game — for example the loops that start with it (Safety Mill \`engage\` → \`"context": ["cut_loop", "feed_loop"]\`) or a one-shot that always follows it — so the user hears the candidate in context: an audition over the representative stretch also plays their decided materials from the cue table (one-shots at their recorded firings, loop cues at their recorded levels, never other candidates) to the end of the stretch. Name only cues of the project's cue table (a trial naming an unknown one is rejected while that project is open); the user can switch the context off to hear the candidate alone. Cues the Events panel groups as firing at the same moment play as context too, without being listed.
- \`candidates\`: 1–6. \`id\` /^[A-Za-z0-9_-]{1,16}$/ unique in the trial, \`label\` ≤ 80 chars, \`hypothesis\` ≤ 400 chars, \`method\` (optional): how the candidate is made — \`"synth"\`, \`"sfx"\`, \`"envelope"\`, \`"layered"\`, \`"onset"\` or \`"bandsplit"\` (see "Ways to make a haptic"). Set it on haptic candidates: the knowledge counts results per method. \`sound\` (optional, haptic trials with a \`scene\`): the sound of the first scene cue's sound pool (WAV name without \`.wav\`) this candidate was made to go with — for example one candidate per sound when the cue has several, each fitted to its length. Studio plays that sound with the candidate's audition (without it: the cue's representative sound; the user can pick another per candidate), and when the cue's variation is \`paired\`, saving puts the candidate at that sound's position in the clip list. \`intensity\` (optional, 0 < x ≤ 1; absent = 1): the starting value of the candidate's strength slider in the rating form — use it to propose a starting strength (for example 0.5 or 0.2) while keeping the WAV full scale. Do not render quieter WAVs to make a candidate start quieter (see "Strength of materials").
- \`source\` is one of:
  - \`{ "kind": "clip", "clipId": "…" }\` — the clip's original (imported) audio.
  - \`{ "kind": "clip", "clipId": "…", "use": "working" }\` — the clip's current processed audio.
  - \`{ "kind": "file", "path": "sources/rain.wav" }\` — relative to \`hapbeat-agent/\`; \`..\` and absolute paths are rejected.
  - \`{ "kind": "recipe", "recipe": { "format": "hapbeat-recipe@1", … } }\` — a generator recipe (ranges under \`recipe\` in catalog.json).
    A recipe layer can also play audio material with \`"source": { "type": "sample", "ref": … }\`, so one recipe mixes recordings with synthesized layers:
    - \`ref\`: \`{ "kind": "file", "path": "sources/tap.wav" }\` (relative to \`hapbeat-agent/\`, same path rule as file sources) or \`{ "kind": "clip", "clipId": "…", "use": "original" | "working" }\` (\`use\` defaults to \`"original"\`).
    - \`rate\` (optional): playback rate; pitch and length change together. \`maxSec\` (optional): each copy is cut at this length with a \`fadeMs\` fade-out. Ranges under \`recipe.sources.sample\` in catalog.json.
    - \`onsetsSec\` (optional, default \`[0]\`): 1–64 start times in seconds (≥ 0, non-decreasing) relative to the layer start; one copy of the material starts at each. \`gainsDb\` (optional): one gain per onset, −60…12 dB each. Overlapping copies add up; copies past the layer end are cut off.
    - The material is mixed to mono and resampled to the recipe's \`sampleRate\`; then the layer's \`am\`, \`envelope\`, \`fadeMs\` and \`gainDb\` apply as usual.
    - \`follow\` (optional): \`{ "mode": "envelope", "smoothMs": 10, "carrier": <synth source> }\` — the layer plays the placed material's amplitude envelope (moving RMS over \`smoothMs\`, 1–200 ms, default 10; × √2 so a full-scale sine reads 1) multiplied by \`carrier\`, a \`sine\` / \`square\` / \`triangle\` / \`noise\` / \`decaying-sine\` source (same fields as a layer source). The sound's timing and loudness shape, on a vibration the actuator plays well (method \`envelope\`).
    - \`onsets\` (optional): \`{ "auto": { "thresholdDb": -30, "minGapMs": 120, "riseDb": 6 }, "hit": <sample ref or synth source>, "hitSec": 0.12 }\` — onsets are detected in the material (its 5 ms level above \`thresholdDb\` re its peak, risen by at least \`riseDb\` (default 6) within 20 ms; at most one per \`minGapMs\`; at most 64) and each gets one copy of \`hit\` (a \`{ "kind": "file" | "clip", … }\` ref or a synth source such as \`{ "type": "decaying-sine", "freqHz": 60, "decayMs": 50 }\`), cut to \`hitSec\` (default: the whole ref / 0.15 s for a synth source), scaled by the material's level at the onset (0–1). The material itself is not played (method \`onset\`). Cannot be combined with \`onsetsSec\` / \`gainsDb\` or \`follow\`.
    - Ranges: \`recipe.sampleFollow\` and \`recipe.sampleOnsets\` in catalog.json.
    - Example — a recorded tap plus a 60 Hz body:
      \`{ "format": "hapbeat-recipe@1", "sampleRate": 48000, "durationSec": 0.4, "seed": 1, "layers": [ { "source": { "type": "sample", "ref": { "kind": "file", "path": "sources/tap.wav" }, "onsetsSec": [0, 0.15], "gainsDb": [0, -3], "maxSec": 0.08 } }, { "source": { "type": "sine", "freqHz": 60 }, "durationSec": 0.25, "gainDb": -6, "envelope": [{ "time": 0, "value": 1 }, { "time": 1, "value": 0 }] } ] }\`
- \`effects\`: array of effect parameter objects applied in order (no \`id\` / \`enabled\`). Allowed types and ranges are in \`catalog.json\` → \`effectTypes\`. Use \`[]\` for none.
  - \`band-split\` (method \`bandsplit\`): \`{ "type": "band-split", "crossoverHz": 150, "carrierHz": 80, "carrierShape": "sine", "highGainDb": 0, "smoothMs": 10 }\` — below \`crossoverHz\` passes unchanged (24 dB/oct); above it the band is replaced by its amplitude envelope (moving RMS over \`smoothMs\`) × a \`carrierHz\` carrier (\`sine\` / \`square\` / \`triangle\`), at \`highGainDb\`.

## Ways to make a haptic (\`method\`)

Real vibration recordings are not assumed. Six ways, from material Studio can reach:

| method | how | good for | build it with |
|---|---|---|---|
| \`synth\` | synthesize from scratch | clean thumps, hums, textures with no matching sound; full control of frequency | \`recipe\` (tone / noise / decaying-sine / impulse-train layers, \`am\`, \`envelope\`) |
| \`sfx\` | the sound effect itself, processed | sounds that already carry low, body-like energy (impacts, rumbles) | \`file\` / \`clip\` source + effects (\`lpf\`, \`freq-shift\`, \`compressor\`, \`envelope\`, …) |
| \`envelope\` | only the sound's loudness shape and timing, on a haptic-friendly carrier | sounds with good timing but little usable low end (whooshes, voices, bright hits) | \`recipe\` \`sample\` layer with \`follow\` |
| \`layered\` | a short stock haptic clip at the head, then a tail made by 2 (\`sfx\`) or 3 (\`envelope\`) | a crisp attack plus the sound's own decay | \`recipe\`: \`sample\` layer of the stock clip (\`maxSec\`) + a later layer from the sound |
| \`onset\` | detect the sound's attacks and put a short haptic hit on each | footsteps, rapid hits, mechanical clicks: rhythm matters more than tone | \`recipe\` \`sample\` layer with \`onsets\` |
| \`bandsplit\` | split at ~150 Hz: the low band as is, the high band as its loudness shape on a tactile-frequency carrier | full-range sounds whose low end is already right and whose highs carry the detail | \`sfx\` source + \`band-split\` effect |

Order of work:
1. Decide the event's sound first (\`target: "sound"\` trials). For its haptic, prefer methods that use that decided sound as material (\`sfx\`, \`envelope\`, \`layered\`, \`onset\`, \`bandsplit\`); the sound WAV is in the project's sound folder (see the Scene project) — copy it under \`hapbeat-agent/sources/\` to reference it.
2. In the first haptic trial of an event, line up candidates made by DIFFERENT methods (for example \`sfx\`, \`envelope\`, \`onset\`, \`synth\`). Then refine within the method that rated best, one axis at a time (the "Recommended workflow" above). \`terms/<slug>.json\` → \`byMethod\` shows which methods tend to work for a term.

Processing: stereo sources are averaged to mono, effects are applied in order, the result is resampled to 48 kHz and, if its peak exceeds 1.0, normalized to 0.98 (recorded as \`autoNormalizedDb\`). A candidate that fails to render gets an \`error\` in its candidates/<cid>.json; the other candidates are still rendered. An invalid request is moved to \`inbox/_rejected/\` with an \`.error.txt\`; fix it and submit again under a new id.

## Receiving ratings

The user rates in Studio and presses Save — that is the signal (there is no separate "send").

1. After a trial: \`wait_for_rating\` (MCP; waits for one trial).
2. Several trials at once, or a long session: watch the files instead —
   - \`haptic-knowledge/trials/**/rating.json\` (new or updated = a rating was saved),
   - \`hapbeat-agent/outbox/*.json\` (requests from the Scene tab).
   Claude Code: a Monitor loop that lists new / changed files every 5 s. A monitor times out: start it again while you work.
3. Read each new outbox file, then move it to \`outbox/_read/\`.
4. For a rating: read each candidate's \`overall\`, \`comment\`, \`useRange\` and the trial's \`comment\`. Every candidate rated ★4+ (\`verdict\` "use") joins the material pool of the trial's first scene cue as tentative, best first, without duplicates; an existing representative stays first (Studio does this on Save when its auto-assign is on). Never add free-plan output (label or source path containing "free plan" / "(free)": not for commercial use), nor what the comments explicitly reject. Then make the next candidates.

## Strength of materials (DEC-086)

- WAV = the shape, always written at full scale (peak −0.5 dBFS).
- \`clips.<name>.intensity\` / \`sounds.<Name>.intensity\` (0..1, absent = 1) = the material's base strength; Studio's editor sets it (Adjust slider) and plays WAV × intensity.
- Route \`gain\` / \`sfx.volume\` (default 1) = the scene multiplier, edited in the Scene tab only. Final output = WAV × intensity × scene multiplier × device volume.
- Studio writes adopted candidates normalized, with their own size as the intensity. Do not bake loudness into WAVs.

## Messages from Studio \`hapbeat-agent-message@1\` (Studio writes, you read)

From the user's clicks: "Change event…" on a firing (Scene tab, \`reassign\`), "Remake…" on a material (\`revise\`), "Request a sound…" (\`sound\`) and "Go to haptics" (\`haptic\`) on an event, all in the Events panel. Files in \`hapbeat-agent/outbox/\`:

\`\`\`json
{ "format": "hapbeat-agent-message@1", "createdAt": "2026-10-05T15:42:00+09:00", "text": "イベントを変える依頼: footstep の 17.37 s の発生を footstep:feeding にしてください", "project": "trex-encounter", "reassign": { "cue": "footstep", "atSec": 17.367, "to": "footstep:feeding" } }
\`\`\`

- \`text\` (≤ 4000 chars) restates the request; \`project\` is context.
- \`reassign\` (optional, from the Scene tab): \`{ "cue": "footstep", "atSec": 17.367, "to": "footstep:feeding", "comment": "…" }\` — the user says the firing of \`cue\` (a cue or \`cue:variant\`) at \`atSec\` of the full recording (\`full.events\` in \`viewer-data.json\`) should be \`to\` instead. It asks you to change the game's routing (which event the game fires there), not the cue table: the table never holds per-moment values. When \`to\` is a new variant of a known cue, Studio has already added it to the table (multipliers only: \`sfxVolume\` 1, \`hapticsGain\` 1) so the user can tune it; add it yourself only if it is still missing. Re-record the scene afterwards.
- \`revise\` (optional, from the Events panel): \`{ "cue": "bite:tear", "target": "sound", "material": "bite_tear_02", "comment": "…" }\` — remake that material of the event (WAV name without .wav) as the comment says: submit a new trial with \`scene.cues\` naming the cue (Studio clears its "remake requested" mark when such a trial arrives). The material stays in the pool as tentative.
- \`sound\` (optional, from the Events panel): \`{ "cue": "rub", "comment": "…" }\` — make (more) sound candidates for the cue as the comment describes (the cue may have none yet). Submit sound trials (\`target\` "sound") with \`scene.cues\` naming the cue; Studio clears its "requested" mark when one arrives.
- \`haptic\` (optional, from the Events panel): \`{ "cue": "bite", "sound": "bite_01", "comment": "…" }\` — make this cue's haptic now, matching its representative sound (\`sound\`: WAV name without .wav; null = the cue has no sound, e.g. a grab). Submit haptic trials (\`target\` "haptic") with \`scene.cues\` naming the cue; Studio clears its "haptic requested" mark when one arrives.
- Files appear complete (the browser commits each \`*.json\` on close); ignore other names (e.g. the browser's \`*.crswap\`). Names sort by time.
- After handling a message, move it to \`outbox/_read/\` (Studio never deletes outbox files).

## Rating \`hapbeat-rating@1\` (Studio writes, you read)

\`\`\`json
{
  "format": "hapbeat-rating@1",
  "trialId": "…",
  "ratedAt": "2026-09-29T15:42:00+09:00",
  "context": { "device": "…", "position": "neck", "deviceWiper": 64, "volumeLabel": "5/10", "note": "…" },
  "best": "B",
  "othersSimilar": true,
  "comment": "B is closest; all of them should be heavier",
  "candidates": {
    "A": { "overall": 3, "verdict": "maybe", "directions": { "roughness": 1, "weight": 0 }, "intensity": 0.6, "comment": "…" }
  },
  "history": []
}
\`\`\`

- Comments are the main information: the user rates mostly in words. Read the trial-level \`comment\` (optional, ≤ 4000 chars: comparisons between candidates, "B is closest, heavier") and every candidate \`comment\` first, then the stars.
- \`overall\` (optional): 1–5 (stars). A candidate may be saved with a comment only and no \`overall\` ("no score"): use its comment, but it is not counted in the knowledge. \`verdict\` is written from it: 4–5 = \`"use"\`, 3 = \`"maybe"\`, 1–2 = \`"no"\` (there is no separate input). \`termMatch\` (per term, −2…+2) is no longer asked: Studio does not write it; older ratings may still have it.
- \`directions\` (optional; Studio no longer asks for it — older ratings may have it; read the comments instead) per axis id: +1 = "should be more <high pole>", −1 = "more <low pole>", 0 = fine. Haptic trials use dimensions.json without \`pleasantness\` (the overall score covers it); \`regularity\` / \`continuity\` only for \`kind\` loop / sequence. Sound trials use their own axes: \`weight\` (bass), \`roughness\` (smooth ↔ rough), \`sharpness\`, \`intensity\` (volume), \`length\` (short ↔ long) and \`regularity\` (regular ↔ random, for every sound trial); they never enter the haptic knowledge.
- Trials set aside for later: the user may skip a trial without rating it (\`dismissed.json\` in its folder with \`"reason": "later"\`; \`"dismissed": true\` in \`index.json\`). It means "not now", not "bad material": it is left out of \`terms/\` and \`byMethod\` and out of the queue until the user restores it; do not read it as a rejection, and do not build on it as if it were rated.
- Short ids: Studio numbers trials in reception order (\`T1\`, \`T2\` …; a candidate is \`T27-B\`). They are in \`index.json\`, \`list_trials\` and \`get_trial\` as \`shortId\`; the user refers to trials and candidates by them.
- \`verdict\`: \`"use"\` / \`"maybe"\` / \`"no"\`, derived from \`overall\` as above; \`useFor\` (optional, ≤ 200 chars, older ratings): what it is good for ("idle growl", "on the out-breath"). Several candidates may be \`"use"\`. There is no "best" input: Studio writes \`best\` = the \`"use"\` candidate with the highest \`overall\` when exactly one has it (absent on a tie or with no \`"use"\`), and, on Save, every \`"use"\` candidate (except free-plan output) is added to the material pool of the first scene cue (see "Receiving ratings"). The order, variants and variation are decided by the user in Studio's Scene tab. When two or more are \`"use"\`, ask the user whether to keep them all as one event's materials (multi-clip route \`clips\` / \`sounds\` with \`variation.pick\`, so each firing varies) or as separate variants (\`cue:variant\`) per \`useFor\`.
- \`useRange\` (optional): \`[[startSec, endSec], …]\` (1–8) — "use only this part" of the rendered candidate (seconds on its 48 kHz audio, after the effects). In the next trial, keep the candidate's source and effects and append \`{ "type": "trim", "start": startSec, "end": endSec }\` as the last effect (one candidate per range when there are several); for a \`sample\` recipe layer you may instead set \`maxSec\` / \`onsetsSec\`. Say in \`rationale\` that the range came from \`useRange\`.
- \`intensity\` (optional, 0–1; absent = 1): the strength the user tried and chose for this candidate with its strength slider (the audition's device gain for a haptic trial, the PC volume for a sound trial). The rendered waveform × \`intensity\` is the wanted level: when you make the next candidates, take this strength as the reference (aim for that level rather than guessing louder or quieter). When the candidate goes into an event, Studio writes the material normalized and sets its intensity = (original peak / 0.944) × \`intensity\` (capped at 1). The slider starts at the trial candidate's \`intensity\` when you proposed one, so a scored candidate records that strength even if the user did not move it. A candidate may hold only \`intensity\` (the user moved the strength off its starting value and gave no score or comment): like "no score", it is not counted in the knowledge.
- \`context.deviceWiper\`: the device's MCP4018 volume wiper (integer 0–127; same as kit-format \`device_wiper\`) — compare volumes with this. \`volumeLabel\` ("level/steps") is only a human aid: the step count depends on the user's settings. Both may be absent.
- \`othersSimilar\` (optional, \`true\`): the user judged every other candidate to be about the same as \`best\` and left them unrated. Do not invent scores for them; treat it as a note that the hypothesis axis made little difference.
- \`history\` holds earlier ratings of the same trial (the user re-rated).

## Term aggregation \`hapbeat-term@1\` (derived)

\`terms/<slug>.json\`: \`dimensions\` (from dimensions.json), \`counts\`, \`good\` (overall ≥ 4 and, when a term match exists, |termMatch| ≤ 0.5), \`tooWeak\` (termMatch ≤ −1), \`tooStrong\` (termMatch ≥ +1; both only from older ratings that have a term match) with per-feature median/p25/p75 (\`peakDb\` / \`rmsDb\` at the rated strength: + 20·log10(\`intensity\`), absent = 1; the shape features as rendered), \`directionVotes\`, \`byMethod\` (per candidate \`method\`, \`"unspecified"\` when absent: \`rated\`, \`good\`, \`tooWeak\`, \`tooStrong\` counts and the \`best\` rated example), \`exemplars\` (top 5 with overall ≥ 4, including their spec and method) and \`counterExamples\` (overall ≤ 2). Slug = term after alias resolution, NFKC, trimmed, katakana → hiragana, file-name characters replaced by \`_\`.

## Features

Computed on the mono signal (candidates: the rendered 48 kHz audio; catalog: each clip's working buffer).

| key | definition |
|---|---|
| durationSec | length in seconds |
| peakDb, rmsDb | dBFS (floored at ${DB_FLOOR}) |
| crestDb | peakDb − rmsDb |
| bandEnergy | energy share per band (sums to 1): ${FEATURE_BANDS.map(b => `\`${b}\``).join(', ')} Hz. Hann-windowed FFT (power of two, at most 2^16 points; longer signals are frame-averaged with 50 % overlap) |
| centroidHz | spectral centroid within 20–1000 Hz |
| dominantHz | frequency of the largest spectral peak within 20–1000 Hz |
| flatness | spectral flatness within 20–1000 Hz (0 = pure tone, 1 = white noise) |
| attackMs | time for the envelope (5 ms RMS, 1 ms hop) to rise from 10 % to 90 % of its maximum |
| decayMs | time from the envelope maximum until it falls to −20 dB (null if it never does) |
| amRateHz | largest peak within 2–80 Hz of the envelope spectrum (mean removed), over the span where the envelope is within −30 dB of its maximum (null if that span is shorter than 50 ms) |
| amDepth | (p95 − p5) / (p95 + p5) of the envelope over that span |
| irregularity | coefficient of variation (std / mean) of the envelope over that span |

## Generating source audio

If you synthesize material (Python, ElevenLabs sound effects, …) save it as WAV (or MP3) under \`hapbeat-agent/sources/\` and reference it with \`{ "kind": "file" }\`. API keys belong to the user's environment variables; Studio does not handle them.

### Using ElevenLabs sound effects (optional)

\`\`\`
POST https://api.elevenlabs.io/v1/sound-generation
xi-api-key: $ELEVENLABS_API_KEY
Content-Type: application/json

{ "text": "stiff canvas rubbing, close up", "duration_seconds": 1.5, "prompt_influence": 0.3, "loop": false }
\`\`\`

- \`duration_seconds\` is optional (0.5–30; omit to let the model choose). \`prompt_influence\` is 0–1 (default 0.3).
- Save the response body as MP3 (or WAV) under \`hapbeat-agent/sources/\`; Studio decodes MP3 fine.
- Cost (checked on 2026-09-29, may change — check ElevenLabs' pricing page): about 40 credits per second when \`duration_seconds\` is set, 200 credits per generation when it is automatic. The free plan (10,000 credits/month) is NOT licensed for commercial use and requires attribution; Starter and above allow commercial use. Tell the user before spending credits.
- Generated sound effects usually carry little energy below ~100 Hz. Plan to add low end (for example \`freq-shift\` down or \`lpf\`; to mix the recording with a synthesized low end, use a \`recipe\` candidate with a \`sample\` layer for the recording and a tone / decaying-sine layer for the low end) and check \`bandEnergy\` of the rendered candidate.

## Rules

- Do not edit \`.hapbeat-editor/\`.
- Do not modify or delete anything under \`haptic-knowledge/trials/\` (raw evidence, append-only).
- Do not hand-edit derived files (\`index.json\`, \`terms/*.json\`, \`catalog.json\`, this guide); Studio regenerates them.
- In \`insights.md\`, only append to the "Proposed" section.
- Parameter ranges: always read \`catalog.json\`; do not guess.
`
}

/** `get_guide` over MCP: the same guide, prefixed with how the tools replace the inbox. */
export function mcpGuideMarkdown(studioVersion: string): string {
  return `> You are connected through the \`hapbeat\` MCP server: use \`submit_trial\` instead of writing to \`hapbeat-agent/inbox/\`, \`get_knowledge\` instead of reading \`haptic-knowledge/\`, \`get_catalog\` instead of \`catalog.json\`, \`wait_for_rating\` / \`get_trial\` for ratings and \`propose_insight\` to append to "Proposed" in insights.md.

${guideMarkdown(studioVersion)}`
}

export function knowledgeReadme(studioVersion: string): string {
  return `${header(studioVersion)}
# haptic-knowledge

Knowledge base of human ratings for Hapbeat vibration designs. Hierarchy: dimensions → terms → trials → candidates → ratings.

| path | owner | notes |
|---|---|---|
| dimensions.json | human | Perceptual dimensions (\`dimensions[]\`: id, ja, en, poles) and vocabulary (\`terms[]\`: term, aliases, dimensions −2..+2, source). Studio writes a seed only when missing. |
| insights.md | human + agents | "Confirmed" is edited by the user; agents append to "Proposed" with evidence. |
| trials/<YYYY-MM>/<id>/ | Studio (append-only) | trial.json, request.json, candidates/<cid>.json, audio/<cid>.wav, rating.json (latest + history). |
| index.json | derived | Regenerated from trials/ on every rating and inbox import. |
| terms/<slug>.json | derived | Regenerated from trials/. A term file not listed in index.json is stale (for example after an alias change) and can be removed by the user. |

Derived files can always be rebuilt from trials/ and dimensions.json. See \`../hapbeat-agent/GUIDE.md\` for the formats.
`
}

export function insightsTemplate(): string {
  return `# Haptic insights

Human-curated findings about Hapbeat vibration and vocabulary. Studio only appends agent proposals (MCP \`propose_insight\`) to the end of "Proposed"; it never edits other parts.

## Confirmed

<!-- The user moves items here after checking them on the device. -->

## Proposed

<!-- Agents append here: one bullet per finding, with evidence (trialId/candidateId). Example:
- ごわごわ: AM depth ≥ 0.7 at 15–20 Hz is rated "just right" more often than 0.4 (20260929-1530-gowagowa-01/B, 20260930-1010-gowagowa-02/A, …).
-->
`
}

export function agentsMd(): string {
  return `# AGENTS.md

This folder is a Hapbeat Studio editor folder.
For haptic (vibration) design requests, follow \`hapbeat-agent/GUIDE.md\`.
Do not edit \`.hapbeat-editor/\` or \`haptic-knowledge/trials/\`.
`
}
export const claudeMd = () => '@AGENTS.md\n'

// ---- catalog.json ----

export interface CatalogClip {
  id: string; name: string; description?: string; project?: string; sourceFileName?: string
  durationSec: number; sampleRate: number; channels: number
  effects: unknown[]; features: HapticFeatures
}
export interface Catalog {
  format: 'hapbeat-catalog@1'
  studioVersion: string
  generatedAt: string
  clips: CatalogClip[]
  effectTypes: Record<string, { params: Record<string, unknown> }>
  recipe: unknown
}

const featureCache = new WeakMap<AudioBuffer, HapticFeatures>()
function bufferFeatures(buffer: AudioBuffer): HapticFeatures {
  let features = featureCache.get(buffer)
  if (!features) {
    features = computeFeatures(mixToMono(Array.from({ length: buffer.numberOfChannels }, (_, ch) => buffer.getChannelData(ch))), buffer.sampleRate)
    featureCache.set(buffer, features)
  }
  return features
}

/** Working-buffer features are cached per AudioBuffer (buffers are immutable in the editor). */
export function buildCatalog(documents: EditorDocument[], studioVersion: string, generatedAt: string): Catalog {
  return {
    format: 'hapbeat-catalog@1', studioVersion, generatedAt,
    clips: documents.map(({ clip, effects }) => ({
      id: clip.id, name: clip.name, description: clip.description, project: clip.project, sourceFileName: clip.sourceFileName,
      durationSec: Math.round(clip.buffer.duration * 1e4) / 1e4, sampleRate: clip.buffer.sampleRate, channels: clip.buffer.numberOfChannels,
      effects: effects.filter(e => e.enabled).map(e => e.params),
      features: bufferFeatures(clip.buffer),
    })),
    effectTypes: Object.fromEntries(Object.entries(EFFECT_RANGES).map(([type, params]) => [type, { params }])),
    recipe: RECIPE_RANGES,
  }
}
