import { describe, expect, it } from 'vitest'
import { EFFECT_RANGES } from './effectRanges'
import type { EditorDocument } from './editorFolder'
import { buildCatalog, guideMarkdown } from './agentGuide'

function fakeBuffer(data: Float32Array, sampleRate: number): AudioBuffer {
  return { numberOfChannels: 1, sampleRate, length: data.length, duration: data.length / sampleRate, getChannelData: () => data } as unknown as AudioBuffer
}

describe('agent guide and catalog', () => {
  it('lists clips with working-buffer features and shared effect ranges', () => {
    const buffer = fakeBuffer(Float32Array.from({ length: 4800 }, (_, i) => 0.5 * Math.sin(2 * Math.PI * 100 * i / 48000)), 48000)
    const doc: EditorDocument = { clip: { id: 'c1', name: 'Cloth', buffer, originalBuffer: buffer, exportSampleRate: 48000 }, effects: [
      { id: 'e1', enabled: true, params: { type: 'gain', gainDb: -3 } },
      { id: 'e2', enabled: false, params: { type: 'reverse' } },
    ], exportAsMono: false }
    const catalog = buildCatalog([doc], '0.8.0', '2026-09-29T15:00:00+09:00')
    expect(catalog.clips[0]).toMatchObject({ id: 'c1', name: 'Cloth', durationSec: 0.1, sampleRate: 48000, channels: 1, effects: [{ type: 'gain', gainDb: -3 }] })
    expect(catalog.clips[0].features.dominantHz).toBeCloseTo(100, -1)
    expect(Object.keys(catalog.effectTypes).sort()).toEqual(Object.keys(EFFECT_RANGES).sort())
    expect(catalog.effectTypes.lpf.params).toBe(EFFECT_RANGES.lpf)
  })

  it('stamps the generated guide', () => {
    expect(guideMarkdown('1.2.3')).toMatch(/^<!-- generated by Hapbeat Studio v1\.2\.3 — do not edit/)
  })

  it('agent store does not start polling on import', async () => {
    const { useAgentTrialStore } = await import('@/stores/agentTrialStore')
    expect(useAgentTrialStore.getState().polling).toBe(false)
    expect(useAgentTrialStore.getState().folder).toBeNull()
  })
})
