/**
 * Generated files for local AI agents: GUIDE.md, haptic-knowledge/README.md,
 * root AGENTS.md / CLAUDE.md, insights.md template and catalog.json.
 * Text only; file writing lives in hapticKnowledge.ts (KnowledgeFolder).
 */
import type { EditorDocument } from '@/utils/editorFolder'
import { EFFECT_RANGES, RECIPE_RANGES } from '@/utils/effectRanges'
import { computeFeatures, mixToMono, FEATURE_BANDS, DB_FLOOR, type HapticFeatures } from '@/utils/hapticFeatures'

const header = (studioVersion: string) => `<!-- generated by Hapbeat Studio v${studioVersion} — do not edit (overwritten on every open) -->`

export function guideMarkdown(studioVersion: string): string {
  return `${header(studioVersion)}
# Hapbeat haptic design — guide for AI agents

> 日本語要約: このフォルダは Hapbeat Studio の波形エディタ用フォルダです。AI エージェントは \`hapbeat-agent/inbox/\` に試行リクエスト（JSON）を置き、ユーザーが Studio で各候補を Hapbeat で触って評価します。評価は \`haptic-knowledge/\` に蓄積されるので、次の提案前に必ず読んでください。Studio は LLM を呼びません。

## MCP tools or files

If a \`hapbeat\` MCP server is available (\`hapbeat-helper mcp\`), prefer its tools: \`get_guide\` → \`get_knowledge\` → \`submit_trial\` → \`wait_for_rating\`. They use the same formats and knowledge base as the files described below. Without it, do the same through the files (\`hapbeat-agent/inbox/\`).

## Purpose

You help the user design vibration (haptic) clips for Hapbeat, a wearable vibrotactile device, from verbal descriptions such as onomatopoeia ("ごわごわ", "ざらざら"). You cannot feel vibration; the user can. So you propose small sets of candidates, the user rates them on the device in Hapbeat Studio, and the ratings accumulate as a knowledge base that you must read before proposing again.

## Folder layout

\`\`\`
<editor folder>/
  .hapbeat-editor/        Studio internal project. Never read or write.
  exports/                User exports.
  hapbeat-agent/
    GUIDE.md              This file (generated).
    catalog.json          Clips in the editor, their features, and parameter ranges (generated).
    inbox/                Put trial requests here: <trialId>.json
    inbox/_rejected/      Invalid requests are moved here with <trialId>.error.txt explaining why.
    sources/              Put source audio you generated (WAV) here.
  haptic-knowledge/
    README.md             Structure of the knowledge base (generated).
    dimensions.json       Perceptual dimensions and vocabulary (human-edited source of truth).
    insights.md           Human/agent notes. Agents may only append to the "Proposed" section.
    index.json            Derived: vocabulary list and trial list.
    terms/<slug>.json     Derived: per-term aggregation of ratings.
    trials/<YYYY-MM>/<trialId>/
      trial.json          Accepted request + receivedAt + studioVersion.
      request.json        Your original request file (moved from inbox).
      candidates/<cid>.json  Resolved spec + features (+ error if rendering failed).
      audio/<cid>.wav     Rendered candidate, 48 kHz mono 16-bit.
      rating.json         The user's rating (latest) + history.
\`\`\`

## Recommended workflow

1. Read \`haptic-knowledge/index.json\`, then the relevant \`terms/<slug>.json\` (compare \`exemplars\` and the feature differences between \`good\`, \`tooWeak\` and \`tooStrong\`) and the "Confirmed" section of \`insights.md\`.
2. Pick ONE hypothesis axis and make 2–4 candidates along it (for example AM depth 0.4 / 0.7 / 0.95). Keep everything else fixed so the rating is interpretable.
3. Write the request to \`hapbeat-agent/inbox/<trialId>.json\` and ask the user to rate it in Studio (Waveform editor → AI trials).
4. Read \`haptic-knowledge/trials/*/<trialId>/rating.json\`. Use \`termMatch\` (too weak / right / too strong) and \`directions\` ("should be more …") to build the next candidates, and set \`parentTrial\` to the previous trial id.
5. When a tendency is consistent over 3 or more trials, append it to the "Proposed" section of \`insights.md\` with evidence (trialId/candidateId). Only the user moves items to "Confirmed".

Write the inbox file atomically if you can (write \`<trialId>.json.tmp\`, then rename). Studio only picks up \`*.json\` files and waits until a file has been unchanged for about 1.5 s.

## Trial request \`hapbeat-trial@1\` (you → Studio)

\`\`\`json
{
  "format": "hapbeat-trial@1",
  "id": "20260929-1530-gowagowa-01",
  "intent": "modify",
  "prompt": "布の音をもっとゴワゴワに",
  "terms": ["ごわごわ"],
  "parentTrial": "20260929-1510-gowagowa-00",
  "agent": { "name": "claude-code", "model": "claude-opus-5-5" },
  "rationale": "Roughness seems to follow AM depth; sweep depth at 18 Hz.",
  "knowledgeUsed": ["terms/ごわごわ.json#exemplars[0]"],
  "candidates": [
    {
      "id": "A",
      "label": "LPF 200 Hz",
      "hypothesis": "lower centroid feels heavier",
      "source": { "kind": "clip", "clipId": "<id from catalog.json>" },
      "effects": [ { "type": "lpf", "frequency": 200, "Q": 0.7 } ]
    }
  ]
}
\`\`\`

- \`id\`: /^[A-Za-z0-9_-]{1,80}$/ and must equal the file name without \`.json\`. Must be new.
- \`intent\`: \`"modify"\` (process existing material) or \`"create"\` (from scratch).
- \`prompt\`: the user's original request (required, ≤ 2000 chars). \`terms\`: 1–5 target words (≤ 40 chars each).
- Optional: \`parentTrial\`, \`agent\`, \`rationale\` (≤ 4000 chars), \`knowledgeUsed\`, \`project\`, \`scene\`, \`kind\`.
- \`project\` (optional): editor project label, 1–80 characters without leading/trailing spaces. Adopted candidates are filed under this project in the editor's clip list; reuse a \`project\` value from catalog.json clips to add to an existing project.
- \`kind\` (optional): \`"oneshot"\` (one event: a hit, a footstep), \`"loop"\` (a continuous texture or hum) or \`"sequence"\` (a repeated series such as consecutive footsteps; reserved — rated like the others for now). The rating form hides the regularity / continuity dimensions for \`"oneshot"\`. When omitted, Studio infers it from the scene cue (a loop cue → loop) and the candidates' length (all ≤ 2 s → oneshot).
- \`scene\` (optional): \`{ "project": "trex-encounter", "cues": ["roar", "roar_impact"] }\` — the game moment the haptic is for. \`project\` is the game project's name (\`project_name\` in its \`Saved/HapticViewer/viewer-lib.json\`), \`cues\` 1–20 cue names from its cue table (/^[A-Za-z0-9_.-]{1,80}$/). While that project is open in Studio's Scene tab, the editor's Scene video panel shows the recorded clip of that moment and plays it with each audition, so the user rates the candidates against the game footage. Omit it when the trial is not for a recorded game moment.
- \`candidates\`: 1–6. \`id\` /^[A-Za-z0-9_-]{1,16}$/ unique in the trial, \`label\` ≤ 80 chars, \`hypothesis\` ≤ 400 chars.
- \`source\` is one of:
  - \`{ "kind": "clip", "clipId": "…" }\` — the clip's original (imported) audio.
  - \`{ "kind": "clip", "clipId": "…", "use": "working" }\` — the clip's current processed audio.
  - \`{ "kind": "file", "path": "sources/rain.wav" }\` — relative to \`hapbeat-agent/\`; \`..\` and absolute paths are rejected.
  - \`{ "kind": "recipe", "recipe": { "format": "hapbeat-recipe@1", … } }\` — a generator recipe (ranges under \`recipe\` in catalog.json).
    A recipe layer can also play audio material with \`"source": { "type": "sample", "ref": … }\`, so one recipe mixes recordings with synthesized layers:
    - \`ref\`: \`{ "kind": "file", "path": "sources/tap.wav" }\` (relative to \`hapbeat-agent/\`, same path rule as file sources) or \`{ "kind": "clip", "clipId": "…", "use": "original" | "working" }\` (\`use\` defaults to \`"original"\`).
    - \`rate\` (optional): playback rate; pitch and length change together. \`maxSec\` (optional): each copy is cut at this length with a \`fadeMs\` fade-out. Ranges under \`recipe.sources.sample\` in catalog.json.
    - \`onsetsSec\` (optional, default \`[0]\`): 1–64 start times in seconds (≥ 0, non-decreasing) relative to the layer start; one copy of the material starts at each. \`gainsDb\` (optional): one gain per onset, −60…12 dB each. Overlapping copies add up; copies past the layer end are cut off.
    - The material is mixed to mono and resampled to the recipe's \`sampleRate\`; then the layer's \`am\`, \`envelope\`, \`fadeMs\` and \`gainDb\` apply as usual.
    - Example — a recorded tap plus a 60 Hz body:
      \`{ "format": "hapbeat-recipe@1", "sampleRate": 48000, "durationSec": 0.4, "seed": 1, "layers": [ { "source": { "type": "sample", "ref": { "kind": "file", "path": "sources/tap.wav" }, "onsetsSec": [0, 0.15], "gainsDb": [0, -3], "maxSec": 0.08 } }, { "source": { "type": "sine", "freqHz": 60 }, "durationSec": 0.25, "gainDb": -6, "envelope": [{ "time": 0, "value": 1 }, { "time": 1, "value": 0 }] } ] }\`
- \`effects\`: array of effect parameter objects applied in order (no \`id\` / \`enabled\`). Allowed types and ranges are in \`catalog.json\` → \`effectTypes\`. Use \`[]\` for none.

Processing: stereo sources are averaged to mono, effects are applied in order, the result is resampled to 48 kHz and, if its peak exceeds 1.0, normalized to 0.98 (recorded as \`autoNormalizedDb\`). A candidate that fails to render gets an \`error\` in its candidates/<cid>.json; the other candidates are still rendered. An invalid request is moved to \`inbox/_rejected/\` with an \`.error.txt\`; fix it and submit again under a new id.

## Rating \`hapbeat-rating@1\` (Studio writes, you read)

\`\`\`json
{
  "format": "hapbeat-rating@1",
  "trialId": "…",
  "ratedAt": "2026-09-29T15:42:00+09:00",
  "context": { "device": "…", "position": "neck", "volumeWiper": 128, "volumeLabel": "5/10", "note": "…" },
  "best": "B",
  "othersSimilar": true,
  "candidates": {
    "A": { "overall": 3, "termMatch": { "ごわごわ": -1 }, "directions": { "roughness": 1, "weight": 0 }, "comment": "…" }
  },
  "history": []
}
\`\`\`

- \`overall\`: 1–5. \`termMatch\` per term: −2 = far too weak, 0 = just right, +2 = too strong.
- \`directions\` per dimension id (see dimensions.json): +1 = "should be more <high pole>", −1 = "more <low pole>", 0 = fine.
- \`context.volumeWiper\`: the device's raw volume wiper value (integer 0–255) — compare volumes with this. \`volumeLabel\` ("level/steps") is only a human aid: the step count depends on the user's settings. Both may be absent.
- \`othersSimilar\` (optional, \`true\`): the user judged every other candidate to be about the same as \`best\` and left them unrated. Do not invent scores for them; treat it as a note that the hypothesis axis made little difference.
- \`history\` holds earlier ratings of the same trial (the user re-rated).

## Term aggregation \`hapbeat-term@1\` (derived)

\`terms/<slug>.json\`: \`dimensions\` (from dimensions.json), \`counts\`, \`good\` (overall ≥ 4 and |termMatch| ≤ 0.5), \`tooWeak\` (termMatch ≤ −1), \`tooStrong\` (termMatch ≥ +1) with per-feature median/p25/p75, \`directionVotes\`, \`exemplars\` (top 5 with overall ≥ 4, including their spec) and \`counterExamples\` (overall ≤ 2). Slug = term after alias resolution, NFKC, trimmed, katakana → hiragana, file-name characters replaced by \`_\`.

## Features

Computed on the mono signal (candidates: the rendered 48 kHz audio; catalog: each clip's working buffer).

| key | definition |
|---|---|
| durationSec | length in seconds |
| peakDb, rmsDb | dBFS (floored at ${DB_FLOOR}) |
| crestDb | peakDb − rmsDb |
| bandEnergy | energy share per band (sums to 1): ${FEATURE_BANDS.map(b => `\`${b}\``).join(', ')} Hz. Hann-windowed FFT (power of two, at most 2^16 points; longer signals are frame-averaged with 50 % overlap) |
| centroidHz | spectral centroid within 20–1000 Hz |
| dominantHz | frequency of the largest spectral peak within 20–1000 Hz |
| flatness | spectral flatness within 20–1000 Hz (0 = pure tone, 1 = white noise) |
| attackMs | time for the envelope (5 ms RMS, 1 ms hop) to rise from 10 % to 90 % of its maximum |
| decayMs | time from the envelope maximum until it falls to −20 dB (null if it never does) |
| amRateHz | largest peak within 2–80 Hz of the envelope spectrum (mean removed), over the span where the envelope is within −30 dB of its maximum (null if that span is shorter than 50 ms) |
| amDepth | (p95 − p5) / (p95 + p5) of the envelope over that span |
| irregularity | coefficient of variation (std / mean) of the envelope over that span |

## Generating source audio

If you synthesize material (Python, ElevenLabs sound effects, …) save it as WAV (or MP3) under \`hapbeat-agent/sources/\` and reference it with \`{ "kind": "file" }\`. API keys belong to the user's environment variables; Studio does not handle them.

### Using ElevenLabs sound effects (optional)

\`\`\`
POST https://api.elevenlabs.io/v1/sound-generation
xi-api-key: $ELEVENLABS_API_KEY
Content-Type: application/json

{ "text": "stiff canvas rubbing, close up", "duration_seconds": 1.5, "prompt_influence": 0.3, "loop": false }
\`\`\`

- \`duration_seconds\` is optional (0.5–30; omit to let the model choose). \`prompt_influence\` is 0–1 (default 0.3).
- Save the response body as MP3 (or WAV) under \`hapbeat-agent/sources/\`; Studio decodes MP3 fine.
- Cost (checked on 2026-09-29, may change — check ElevenLabs' pricing page): about 40 credits per second when \`duration_seconds\` is set, 200 credits per generation when it is automatic. The free plan (10,000 credits/month) is NOT licensed for commercial use and requires attribution; Starter and above allow commercial use. Tell the user before spending credits.
- Generated sound effects usually carry little energy below ~100 Hz. Plan to add low end (for example \`freq-shift\` down or \`lpf\`; to mix the recording with a synthesized low end, use a \`recipe\` candidate with a \`sample\` layer for the recording and a tone / decaying-sine layer for the low end) and check \`bandEnergy\` of the rendered candidate.

## Rules

- Do not edit \`.hapbeat-editor/\`.
- Do not modify or delete anything under \`haptic-knowledge/trials/\` (raw evidence, append-only).
- Do not hand-edit derived files (\`index.json\`, \`terms/*.json\`, \`catalog.json\`, this guide); Studio regenerates them.
- In \`insights.md\`, only append to the "Proposed" section.
- Parameter ranges: always read \`catalog.json\`; do not guess.
`
}

/** `get_guide` over MCP: the same guide, prefixed with how the tools replace the inbox. */
export function mcpGuideMarkdown(studioVersion: string): string {
  return `> You are connected through the \`hapbeat\` MCP server: use \`submit_trial\` instead of writing to \`hapbeat-agent/inbox/\`, \`get_knowledge\` instead of reading \`haptic-knowledge/\`, \`get_catalog\` instead of \`catalog.json\`, \`wait_for_rating\` / \`get_trial\` for ratings and \`propose_insight\` to append to "Proposed" in insights.md.

${guideMarkdown(studioVersion)}`
}

export function knowledgeReadme(studioVersion: string): string {
  return `${header(studioVersion)}
# haptic-knowledge

Knowledge base of human ratings for Hapbeat vibration designs. Hierarchy: dimensions → terms → trials → candidates → ratings.

| path | owner | notes |
|---|---|---|
| dimensions.json | human | Perceptual dimensions (\`dimensions[]\`: id, ja, en, poles) and vocabulary (\`terms[]\`: term, aliases, dimensions −2..+2, source). Studio writes a seed only when missing. |
| insights.md | human + agents | "Confirmed" is edited by the user; agents append to "Proposed" with evidence. |
| trials/<YYYY-MM>/<id>/ | Studio (append-only) | trial.json, request.json, candidates/<cid>.json, audio/<cid>.wav, rating.json (latest + history). |
| index.json | derived | Regenerated from trials/ on every rating and inbox import. |
| terms/<slug>.json | derived | Regenerated from trials/. A term file not listed in index.json is stale (for example after an alias change) and can be removed by the user. |

Derived files can always be rebuilt from trials/ and dimensions.json. See \`../hapbeat-agent/GUIDE.md\` for the formats.
`
}

export function insightsTemplate(): string {
  return `# Haptic insights

Human-curated findings about Hapbeat vibration and vocabulary. Studio only appends agent proposals (MCP \`propose_insight\`) to the end of "Proposed"; it never edits other parts.

## Confirmed

<!-- The user moves items here after checking them on the device. -->

## Proposed

<!-- Agents append here: one bullet per finding, with evidence (trialId/candidateId). Example:
- ごわごわ: AM depth ≥ 0.7 at 15–20 Hz is rated "just right" more often than 0.4 (20260929-1530-gowagowa-01/B, 20260930-1010-gowagowa-02/A, …).
-->
`
}

export function agentsMd(): string {
  return `# AGENTS.md

This folder is a Hapbeat Studio editor folder.
For haptic (vibration) design requests, follow \`hapbeat-agent/GUIDE.md\`.
Do not edit \`.hapbeat-editor/\` or \`haptic-knowledge/trials/\`.
`
}
export const claudeMd = () => '@AGENTS.md\n'

// ---- catalog.json ----

export interface CatalogClip {
  id: string; name: string; description?: string; project?: string; sourceFileName?: string
  durationSec: number; sampleRate: number; channels: number
  effects: unknown[]; features: HapticFeatures
}
export interface Catalog {
  format: 'hapbeat-catalog@1'
  studioVersion: string
  generatedAt: string
  clips: CatalogClip[]
  effectTypes: Record<string, { params: Record<string, unknown> }>
  recipe: unknown
}

const featureCache = new WeakMap<AudioBuffer, HapticFeatures>()
function bufferFeatures(buffer: AudioBuffer): HapticFeatures {
  let features = featureCache.get(buffer)
  if (!features) {
    features = computeFeatures(mixToMono(Array.from({ length: buffer.numberOfChannels }, (_, ch) => buffer.getChannelData(ch))), buffer.sampleRate)
    featureCache.set(buffer, features)
  }
  return features
}

/** Working-buffer features are cached per AudioBuffer (buffers are immutable in the editor). */
export function buildCatalog(documents: EditorDocument[], studioVersion: string, generatedAt: string): Catalog {
  return {
    format: 'hapbeat-catalog@1', studioVersion, generatedAt,
    clips: documents.map(({ clip, effects }) => ({
      id: clip.id, name: clip.name, description: clip.description, project: clip.project, sourceFileName: clip.sourceFileName,
      durationSec: Math.round(clip.buffer.duration * 1e4) / 1e4, sampleRate: clip.buffer.sampleRate, channels: clip.buffer.numberOfChannels,
      effects: effects.filter(e => e.enabled).map(e => e.params),
      features: bufferFeatures(clip.buffer),
    })),
    effectTypes: Object.fromEntries(Object.entries(EFFECT_RANGES).map(([type, params]) => [type, { params }])),
    recipe: RECIPE_RANGES,
  }
}
